name: projeto_2024
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  at_viz: ^0.0.2
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  fl_chart: ^0.68.0
  fluentui_system_icons: ^1.1.238
  flutter:
    sdk: flutter
  flutter_web_auth: ^0.5.0
  http: ^1.2.0
  provider: ^6.1.2
  webview_cookie_manager: ^2.0.6
  intl: ^0.18.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
